### ISSUE TITLE
Visual representation of app

### ISSUE THREAD

**Issue by liamaxelrod** [DIT113-V22/group-05#13]
Visual representation of the app

**Comment by liamaxelrod** [comment]
As a user I want easy to understand buttons and a dynamic color scheme

Acceptance Criteria:

- [x] implement the color scheme specified in the github wiki, meeting notes, entry 7 in all parts of the app  
- [ ] Create icons to buttons
- [x] make buttons react to user input
- [x] Ask outside member of group 5 for there understanding of the visual representation of the android app

**Comment by Valkama1** [comment]
Old issue, no longer relevant to project. Closed.

**Comment by o55ian** [comment]
Addressed further in https://github.com/DIT113-V22/group-05/issues/23
