### ISSUE TITLE
Engine control

### ISSUE THREAD

**Issue by Valkama1** [DIT113-V22/group-05#15]
As a user I want rudimentary control over the car, comparable to a train. This control will be through the serial.

**Acceptance criteria:**
- [x] It is possible to set the engines to a specified percentage
- [x] The engines always move in the same direction
- [x] The car can drive forwards
- [x] The car can reverse
- [x] The car can stop
- [x] Will be tested manually

**Comment by liamaxelrod** [comment]
It is possible to set the engines to a specified percentage

Was implemented in spring 2
