### ISSUE TITLE
App Design

### ISSUE THREAD

**Issue by AlbinKarlsson** [DIT113-V22/group-05#23]
As a driver I want to have a pretty interface and an easy to use, intuitive app. 

## Acceptance Criteria: 
- [x] Ensure that the colour scheme specified below are the only colours used in the app
- [x] Implement changes that have been voted on into the android app.
- [x] One user should test it and approve of the design.
- [x] Ensure that adjacent entities like buttons and background have distinct colours to ensure visibility
- [x] Add Intractable icons to make app use more Intuitive 

### HTML Hex Code for the project
|  **HEX CODE**  | **COLOR**  | 
| --- |--- |
|  000000 | Black  |   
|  14213D | Oxford Blue  |   
|  FCA311 | Orange Web  |
|  E5E5E5 | Platinum  |   
|  FFFFFF | White  |   

![image](https://user-images.githubusercontent.com/101330774/169653121-d1f01d90-1dfb-4f87-a141-29423b4c164d.png)

**Comment by o55ian** [comment]
<img width="566" alt="Screenshot 2022-05-17 111017" src="https://user-images.githubusercontent.com/90551861/168775214-389d470d-346b-4802-80a9-3806a6241911.png">

**Comment by o55ian** [comment]
<img width="174" alt="Screenshot 2022-05-17 111514" src="https://user-images.githubusercontent.com/90551861/168776334-41de133e-9dab-4ab6-8ec7-d5b3432ca677.png">
<img width="175" alt="Screenshot 2022-05-17 111543" src="https://user-images.githubusercontent.com/90551861/168776367-cfbbf37b-e478-4843-b0b8-f5985d5f99dd.png">
<img width="185" alt="Screenshot 2022-05-17 111631" src="https://user-images.githubusercontent.com/90551861/168776421-0ef012f1-c1da-4460-9948-a414af732611.png">
