### ISSUE TITLE
Limit reverse speed

### ISSUE THREAD

**Issue by Valkama1** [DIT113-V22/group-05#42]
As a user I don't want the car to reverse as fast as it can drive forwards.

**Acceptance criteria:**
- [x] The car should only reverse at 50% of the normal driving speed.
- [x] The car should always drive backwards at 50% of the normal speed no matter other factors, such as driving forwards first or turning. 
- [x] The max reversing speed does not surpass 50%.

**Comment by AlbinKarlsson** [comment]
On hold, this issue was more complex than exoected. We need to put more time on. it
