### ISSUE TITLE
Incoming avoidance from the sides

### ISSUE THREAD

**Issue by liamaxelrod** [DIT113-V22/group-05#48]
The simulated car will register when an object is sensed by either the side sensors on the car. When it senses an object that is on the side of the car it will speed up forward to try to avoid the object coming from the sides.

## Acceptance Criteria:

- [x] When the side of the car sensors registers an object it will perform an evasive maneuver. 
- [x] When evasive maneuver takes effect the car will speed forward to avoid the registered object on its side.
- [x] When the car no longer registers an object on its side it will continue to move forward one or two seconds.
- [x] When the car has finished it at evasive maneuver the car will come to a standstill waiting for the next command.

**Comment by o55ian** [comment]
Due to having to redo designOverhaul in Design 2 and later Design 3. The time needed to meet the requirments for this issue was not available.
