### ISSUE TITLE
Register collision

### ISSUE THREAD

**Issue by liamaxelrod** [DIT113-V22/group-05#49]
The car will be able to register when it's in a collision

## Acceptance Criteria:

- [x] The car will registered been in a collision under the following criteria.
	- [x] The car will register a collision if the angle of change is above  55 or last -55
	- [x] when the car is stationary and and the car moved even though it did not get input from the user it will register a collision if the angle is increased more than two
- [x] the car will register a collision if one of the ultra sensors registers a distance of 23 or under

**Comment by platisd** [comment]
Why the underscores in the title? :}
