### ISSUE TITLE
Control the car through a wireless connection

### ISSUE THREAD

**Issue by Lindet94** [DIT113-V22/group-05#5]

**Comment by AlbinKarlsson** [comment]
As a user I want to be able to control the car through the android app not the serial in the simulator.

**Acceptance criteria:**

- [x] A stable connection between the car and pc is established via MQTT
- [x] The CMD is connected to control the car
- [x] The car engines respond to commands sent from the android app on PC
- [x] The car sends sensor data to the android app on a PC
